ポケモンのテーブルni作成。seeds.rbの内容変更。
U-Yuri/PokeCa pull request #14
Opened 2024-01-28 08:34 UTC by ktomomi0333

2024-01-28 09:08 UTC, ktomomi0333 commented
①下記コマンドでテーブルを作成するもskillが2つあるため、「rails db:migrate」を実行するとエラーが出てしまい失敗。
tomomikikuchi@tomominoMacBook-Air~/Desktop/PokeCa$ rails g model Pokemon sinka:string name:string special:string hp:integer zokusei:string zokusei:references skill:references skill:references

②カラムに別名をつける方法でやり直し。（サイト:　https://qiita.com/j-sunaga/items/ee1fb558807c04243f0f)

③マイグレーションファイルを作成。
「rails g model Pokemon sinka:string name:string special:string hp:integer zokusei:string」

④マイグレーションファイルを書き換え
<img width="414" alt="スクリーンショット 2024-01-28 17 56 33" src="https://github.com/U-Yuri/PokeCa/assets/108171290/4c777c23-24c7-4775-b061-0050454823fe">

⑤rails db:migrate実行
【schema.rbの内容の変更】
<img width="389" alt="スクリーンショット 2024-01-28 17 58 33" src="https://github.com/U-Yuri/PokeCa/assets/108171290/0e16fedc-5403-48ab-98ad-4b8915c0e1dd">

⑥pokemon.rbに記入
【pokemon.rb】
class Pokemon < ApplicationRecord
   belongs_to :skill, class_name: 'Skill', foreign_key: :skill1_id
   belongs_to :skill, class_name: 'Skill', foreign_key: :skill2_id
   belongs_to :skill, class_name: 'Tokusei', foreign_key: :tokusei_id
end

⑦skill.rbとtokusei.rbの記入
【tokusei.rb】
  class Tokusei < ApplicationRecord
  has_many :pokemons, foreign_key: :tokusei_id
end

【skill.rb】
class Skill < ApplicationRecord
   has_many :pokemons, foreign_key: :skill1_id
   has_many :pokemons, foreign_key: :skill2_id
end

⑧確認
<img width="1433" alt="スクリーンショット 2024-01-28 18 03 56" src="https://github.com/U-Yuri/PokeCa/assets/108171290/0c7443d9-994e-4c45-a565-447a184f6236">

誤りがあれば修正します。
seeds.rbのpokemonsテーブルにもデータを追記。
skillsテーブルにもポケモンに属する技を追記しています。
seeds.rbとりあえず記入はしましたが、調べて記入方法間違えていたらこちらも訂正します。
ご確認よろしくお願いいたします。

2024-02-02 11:27 UTC, U-Yuri requested changes
いつものテスト方法(Rails db)では大丈夫でした。

しかしrubyで確認するとエラーがあったのでエラー内容と対応法記載します。


■rubyでdbの情報を取れるか確認する方法

①`rails console`でrailsのirbを立ち上げる

②ポケモンのビッパの情報をみる。
```ruby
irb(main):001> Pokemon.find_by(name:'ビッパ')
Pokemon Load (0.4ms)  SELECT "pokemons".* FROM "pokemons" WHERE "pokemons"."name" = ? LIMIT ?  [["name", "ビッパ"], ["LIMIT", 1]]
=> 
#<Pokemon:0x0000000106901e18
 id: 1,
 sinka: "たね",
 name: "ビッパ",
 special: "",
 hp: 60,
 zokusei: "無色",
 tokusei_id: 2,
 skill1_id: 3,
 skill2_id: nil,
 created_at: Fri, 02 Feb 2024 04:45:12.680273000 UTC +00:00,
 updated_at: Fri, 02 Feb 2024 04:45:12.680273000 UTC +00:00>
```
ビッパの情報を確認できたのでOK。

②ポケモンのビッパのスキル１の情報をとる
→まずはビッパの情報をpという変数にいれる
```ruby
irb(main):002> p = Pokemon.find_by(name:'ビッパ')
```

→次に`p.skill1`でスキルの情報をとる

```ruby
irb(main):003> p.skill1
/Users/macuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activemodel-7.0.8/lib/active_model/attribute_methods.rb:450:in `method_missing': undefined method `skill1' for #<Pokemon id: 1, sinka: "たね", name: "ビッパ", special: "", hp: 60, zokusei: "無色", tokusei_id: 2, skill1_id: 3, skill2_id: nil, created_at: "2024-02-02 04:45:12.680273000 +0000", updated_at: "2024-02-02 04:45:12.680273000 +0000"> (NoMethodError)
Did you mean?  skill
               skill=

```

すると上記のように「skill1というクラスはないですよ」的なエラーが出るためビッパのスキル１の情報をとることができない。

ちなみに`p.tokusei`もエラー。

→`add/models/pokemon.rb`の記述に問題あり。

→irbで記述した`p:skill1`と`belongs_to :skill, class_name: 'Skill', foreign_key: :skill1_id`の`belongs_to :`の後の`skill,'は同じにしないといけない。でもskill1というクラスはないので`class_name: 'Skill'`を記述する。

→特性に関しては`belongs_to :skill`がskillになっているので`tokusei`に修正しないといけない。

これらを踏まえ、`add/models/pokemon.rb`を以下のようにコードを書き換える必要あり。

```ruby
class Pokemon < ApplicationRecord
  belongs_to :skill1, class_name: 'Skill', foreign_key: :skill1_id
  belongs_to :skill2, class_name: 'Skill', foreign_key: :skill2_id
  belongs_to :tokusei
end
```
※特性の後の`class_name: 'Tokusei', foreign_key: :tokusei_id`を削除しているのは、デフォルトに含まれているので記載する必要がないらしい。

③ここまで対応し'$ rails db:reset 'し再度`$ rails console`で確認しようとすると、'$ rails db:reset 'で以下のエラー。

```bash
$ rails db:reset
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Skill2 must exist
/Users/macuser/PokeCa/Pokeca/db/seeds.rb:96:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)
```
skill2がないですよ的なエラー。

skill2の情報が「nil」であるためのエラー。

④`add/models/pokemon.rb`のskill2の最後にnilでも許可する`optional: true`を追記。
```ruby
class Pokemon < ApplicationRecord
  belongs_to :skill1, class_name: 'Skill', foreign_key: :skill1_id
  belongs_to :skill2, class_name: 'Skill', foreign_key: :skill2_id, optional: true
  belongs_to :tokusei
end
```

⑤再度`rails console`で確認する

```ruby
irb(main):002> p = Pokemon.find_by(name:'ビッパ')`
※省略
irb(main):004> p.skill1
  Skill Load (0.2ms)  SELECT "skills".* FROM "skills" WHERE "skills"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
=> 
#<Skill:0x0000000113b789f0
 id: 3,
 name: "ひっさつまえば",
 koka: "コインを1回投げウラなら、このワザは失敗。",
 attack_point: 30,
 symbol: "",

irb(main):003> p.skill2
=> nil
```

■`seeds.rb`に関して

空白の部分は`nil`に変更した方が「''」より良いらしい

```ruby
# ポケモンのデータ
Pokemon.create!(
  name: 'ビッパ',
  sinka: 'たね',
  zokusei: '無色',
  hp: '60',
  special: nil,
  tokusei_id: '2',
  skill1_id: '3',
  skill2_id: nil
)

Pokemon.create!(
  name: 'ビーダル',
  sinka: '1進化',
  zokusei: '無色',
  hp: '120',
  special: nil,
  tokusei_id: '1',
  skill1_id: '4',
  skill2_id: nil
)
```

2024-02-03 04:15 UTC, ktomomi0333 commented on db/migrate/20240128014028_create_pokemons.rb
> +      t.string :sinka
cde2c07
修正しました。

2024-02-03 04:16 UTC, ktomomi0333 commented on db/migrate/20240128014028_create_pokemons.rb
> +      t.string :name
cde2c07
修正しました。

2024-02-03 04:17 UTC, ktomomi0333 commented on db/migrate/20240128014028_create_pokemons.rb
> +      t.integer :skill1_id, index: true
cde2c07
修正しました。

2024-02-03 04:17 UTC, ktomomi0333 commented on db/migrate/20240128014028_create_pokemons.rb
> +      t.string :zokusei
cde2c07
修正しました。

2024-02-03 04:32 UTC, U-Yuri approved these changes
OKです！

2024-02-03 04:33 UTC, merged