トップページのレイアウト変更
U-Yuri/PokeCa pull request #3
Opened 2024-01-02 07:43 UTC by ktomomi0333

練習のためトップページ変更！
CSS忘れているので練習のためいじってみました！
多分間違っているところとかあるし、デザインもダサいと思うので、また後々変えることを予定して書いてます！
練習としてプルリクエスト！急ぎでないので空いている時にでも確認お願いします！

2024-01-05 02:07 UTC, U-Yuri approved these changes
レスポンシブ対応は後々対応しましょう！てことでとりあえずOKです！

2024-01-05 07:05 UTC, U-Yuri requested changes
![スクリーンショット 2024-01-05 11 41 11](https://github.com/U-Yuri/PokeCa/assets/80314978/b455db4f-1894-4f13-9131-709acc677201)
このラジオボタン、全部選択できるからどれかひとつ選択できるように対応お願いします！

2024-01-20 23:30 UTC, ktomomi0333 commented
ラジオボタンひとつだけ選択できるように変更しました。
ご確認お願いします。

2024-01-21 01:00 UTC, U-Yuri approved these changes
確認しました！OKです！

2024-01-21 01:00 UTC, merged